using Microsoft.AspNetCore.Components.Web;
using Spellslinger.Models;

namespace Spellslinger.Services;

/// <summary>
/// The main game state.
/// </summary>
public interface IGame
{
	/// <summary>
	/// The map on which the player is curerntly located.
	/// </summary>
	public Map CurrentMap { get; set; }

	/// <summary>
	/// The log of messages generated by the game.
	/// </summary>
	public IList<string> Log { get; }

	/// <summary>
	/// The player character, or null if the player is dead.
	/// </summary>
	public Actor Player { get; set; }

	/// <summary>
	/// A random number generator.
	/// </summary>
	public Random Rng { get; }

	/// <summary>
	/// Sends keyboard input to the game.
	/// </summary>
	/// <param name="e"></param>
	public void AcceptKeyboardInput(KeyboardEventArgs e);
}
